temp_dir: '/tmp/'
segment_prefix: 'human_planet'
index_prefix: 'human_planet'

# type of logging: STDOUT, FILE
log_type: 'STDOUT'
#log_type: 'FILE'
#log_file: '/tmp/streamer.log'
# levels: DEBUG, INFO, WARN, ERROR
log_level: 'DEBUG'

# where the origin video is going to come from
input_location: '/Users/bartuer/Movies/hp_2min.mov'

# segment length in seconds
segment_length: 10 

# this is the URL where the stream (ts) files will end up
# if this location is the same as the location where the m3u8 
# index is then leave it blank
# url_prefix: ''

# url_prefix: "http://#{`hostname`}/"
url_prefix: "http://192.168.0.132/"

# how many segments to keep in the index
index_segment_count: 15

# this command is used for multirate encodings and is what pushes the encoders
source_command: 'cat %s'

# This is the location of the segmenter
segmenter_binary: 'live_segmenter'

# the encoding profile to use
encoding_profile: ['480p_440k', '640p_800k', '960p_1200k']

# The upload profile to use
transfer_profile: 'copy_dev'


#
# Encoding profiles
#
480p_440k:
  encode_command: "hb -i %s -o %s -e x264 --x264-preset fast --x264-profile baseline  --x264-tune film  -X 480  -b 320 -E ca_aac -B 128 -9 -r 29.97 -vfr -f mp4 -O -m"
  packet_command: "ffmpeg -er 4 -vbsf h264_mp4toannexb -i %s -f mpegts -acodec copy -vcodec copy - | %s %s %s %s %s"
  bandwidth: 440000

640p_800k:
  encode_command: "hb -i %s -o %s -e x264 --x264-preset medium  --x264-profile main  --x264-tune film  -X 640  -b 640 -E ca_aac -B 128 -9 -r 29.97 -vfr -f mp4 -O -m"
  packet_command: "ffmpeg -er 4 -vbsf h264_mp4toannexb -i %s -f mpegts -acodec copy -vcodec copy - | %s %s %s %s %s"
  bandwidth: 800000

960p_1200k:
  encode_command: "hb -i %s -o %s -e x264 --x264-preset medium  --x264-profile main  --x264-tune film  -X 960  -b 960 -E ca_aac -B 128 -9 -r 29.97 -vfr -f mp4 -O -m"
  packet_command: "ffmpeg -er 4 -vbsf h264_mp4toannexb -i %s -f mpegts -acodec copy -vcodec copy - | %s %s %s %s %s"
  bandwidth: 800000

#
# Transfer profiles
#

copy_dev:
  transfer_type: 'copy'
  # directory: "#{`$HOME`}/Sites"
  directory: "/Users/bartuer/Sites"